### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by JadeOfMaar** [JadeOfMaar/RealisticResources#1]
### Default/CRP
* [ ] Convert-O-Tron patches
* [ ] Drill-O-Matic patches
* [ ] Extra: Optional non-nerf for Ore (...maybe)

__(Converter Module) Main Fuel Processing__

| Output | Inputs |
| --- | --- |
| LiquidFuel | Ore |
| LFO | LqdHydrogen + LqdCO2 |
| MonoPropellant | LqdHydrogen + LqdNitrogen |
| Oxidizer | LqdOxygen |
| LH2O | Water |
| Methalox | LqdHydrogen + LqdCO2 |

__(Generator Module) Cryo-based Fuel Prep__

| Output | Inputs |
| --- | --- |
| LqdCO2 | CarbonDioxide |
| LqdHydrogen | Hydrogen |
| LqdMethane | Methane |
| LqdNitrogen | Nitrogen |
| LqdOxygen | Oxygen |

### Classic Stock integration
* [ ] Resources
* [ ] OmniConverters (for CRP)
